// AnalyticsService - Business Intelligence for EPIR AI
export class AnalyticsService {
  constructor(db) {
    this.db = db;
  }

  /**
   * Pobiera "Gorące Leady" - gości z wysokim scoringiem, którzy jeszcze nie kupili
   * (nie zostali zmergowani z customer_id)
   */
  async getHotLeads(limit = 20) {
    const query = `
      SELECT 
        client_id, 
        lead_score, 
        last_seen,
        ai_context
      FROM client_profiles 
      WHERE lead_score > 0
      ORDER BY lead_score DESC, last_seen DESC 
      LIMIT ?
    `;

    const result = await this.db.prepare(query).bind(limit).all();
    
    // Parse ai_context/preferences to extract metal/ring_size/intent if possible
    // For now we return raw data or simple mapping
    return result.results.map(row => {
        let details = {};
        try { details = JSON.parse(row.ai_context || '[]'); } catch(e){}
        // Simple extraction logic could go here if we had structured columns
        // Assuming the query in prompt had columns that might need migration, 
        // but for now 0002 migration only added:
        // client_id, created_at, last_seen, email, phone, first_name, total_sessions, lead_score, conversion_probability, ai_context, preferences
        // The prompt requested 'ring_size', 'preferred_metal', 'purchase_intent' in SELECT
        // But these columns DO NOT EXIST in the schema I just created (0002_client_profiles.sql).
        // I should probably adjust the query to what I actually have or use JSON extract if D1 supports it, or parse in JS.
        
        let contextArray = [];
        try {
            if (typeof row.ai_context === 'string') contextArray = JSON.parse(row.ai_context);
        } catch(e) {}

        // Mocking extraction from context for the display
        return {
            ...row,
            ring_size: this.extractFromContext(contextArray, 'rozmiar'),
            preferred_metal: this.extractFromContext(contextArray, 'złoto', 'srebro'),
            purchase_intent: row.lead_score > 50 ? 'High' : 'Medium'
        };
    });
  }

  extractFromContext(context, ...keywords) {
      if(!Array.isArray(context)) return null;
      for (const item of context) {
          const str = typeof item === 'string' ? item.toLowerCase() : JSON.stringify(item).toLowerCase();
          for (const kw of keywords) {
              if (str.includes(kw.toLowerCase())) return kw;
          }
      }
      return null;
  }

  /**
   * Generuje raport statystyk ogólnych (KPI)
   */
  async getDailyStats() {
    // Pobieramy statystyki z ostatnich 24h
    // D1 stores dates as integers usually if generated by Date.now()
    const oneDayAgo = Date.now() - 86400000;
    
    const stats = await this.db.prepare(`
      SELECT 
        COUNT(*) as total_visitors,
        SUM(CASE WHEN lead_score > 20 THEN 1 ELSE 0 END) as qualified_leads,
        AVG(lead_score) as avg_engagement
      FROM client_profiles
      WHERE last_seen > ?
    `).bind(oneDayAgo).first();

    return stats;
  }
}
